# Generated by Django 5.0 on 2025-12-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipoincidencia_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoincidencia',
            name='nombre',
            field=models.CharField(default='Incidencia', max_length=100),
        ),
    ]
